# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vkaccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('token', models.CharField(max_length=300)),
                ('vk_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='vkaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glue.Vkaccount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='vkaccount',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='glue.Vkaccount'),
            preserve_default=False,
        ),
    ]
