# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('glue', '0002_auto_20161029_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='story',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='vkaccount',
        ),
        migrations.RemoveField(
            model_name='post',
            name='community',
        ),
        migrations.RemoveField(
            model_name='post',
            name='vkaccount',
        ),
        migrations.RemoveField(
            model_name='story',
            name='post',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
