# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('glue', '0003_auto_20161029_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('is_posted', models.BooleanField(default=False)),
                ('vk_id', models.IntegerField(blank=True, null=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glue.Community')),
                ('vkaccount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glue.Vkaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='story_posting.Story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='vkaccount',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glue.Vkaccount'),
        ),
    ]
