# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_posting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vk_id',
            new_name='vk_id_real',
        ),
        migrations.AddField(
            model_name='post',
            name='is_proposed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='vk_id_request',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
