# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_posting', '0002_auto_20161029_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='story_is_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='story',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
