# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_posting', '0004_remove_story_is_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='parent_post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='story', to='story_posting.Post'),
            preserve_default=False,
        ),
    ]
