# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('story_posting', '0006_auto_20161029_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='community',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='glue.Community'),
        ),
    ]
